logging.file: logs/dev_app.log
logging.pattern.console: "%d %-5level %logger : %msg%n"
logging.pattern.file: "%d %-5level [%thread] %logger : %msg%n"
logging.level.: INFO
logging.level.org.springframework.security: DEBUG


server:
  port: 9011
  session-timeout: 6000
  connection-timeout: 120000
  servlet:
    context-path: /cash-flow-service

spring.datasource.url : jdbc:mysql://172.17.0.2/CFS?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username : root
spring.datasource.password : root
spring.datasource.driver-class-name : com.mysql.jdbc.Driver
spring.datasource.testOnBorrow : true
spring.jpa.database-platform : org.hibernate.dialect.MySQL57Dialect
spring.datasource.validationQuery : SELECT 1
spring.jpa.show-sql : true
spring.jpa.hibernate.ddl-auto : update
spring.jpa.generate-ddl : true
spring.jpa.properties.hibernate.cache.use_second_level_cache : false
spring.jpa.properties.hibernate.cache.use_query_cache : false
spring.jpa.properties.hibernate.cache.use_structured_entries : false
spring.jpa.properties.hibernate.cache.use_minimal_puts : false
spring.jpa.properties.hibernate.cache.generate_statistics : false

services.status:
  cart-enabled: true
  perfios-enabled: true
  
document.upload_file_path: /home/vagrant/images
document.local_upload_file_path: /home/vagrant/images
document.permitted_content_types: application/pdf

perfios.impl.version: 1
perfios.callBackUrl: abc
perfios.vendor: pfc
perfios.returnUrl: abc
perfios.integration.userName: abc
perfios.integration.key: abc
perfios.retry.count: 5
perfios.product.name: abc
perfios.integration.url: abc
perfios.simulator: abc
perfios.private-key-path: abc
perfios.productType: lll
perfios.bsa.upload.callBackUrl: abs

perfios.bsa.product.map:
   cartenabled: yes
   v: a

req.prefix: HFT
esb.url: https://osbuat.aubankuat.in/

au.username: au
au.password: pass
au.key: abcd1234efg


au.common.url: as

cloud.bucketFolder:
