version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  spring-app:
    image: cfs:cfs
    container_name: spring-app-container
    ports:
      - "9011:9011"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/CFS?useUnicode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_TESTONBORROW: 'true'
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL57Dialect
      SPRING_DATASOURCE_VALIDATIONQUERY: SELECT 1
      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 5
      SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MINIMUMIDLE: 1
      SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: 600000
      SPRING_DATASOURCE_HIKARI_MAXLIFETIME: 1800000
      SPRING_JPA_SHOW-SQL: 'true'
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      SPRING_JPA_GENERATE-DDL: 'false'
      SPRING_JPA_PROPERTIES_HIBERNATE_CACHE_USE_SECOND_LEVEL_CACHE: 'false'
      SPRING_JPA_PROPERTIES_HIBERNATE_CACHE_USE_QUERY_CACHE: 'false'
      SPRING_JPA_PROPERTIES_HIBERNATE_CACHE_USE_STRUCTURED_ENTRIES: 'false'
      SPRING_JPA_PROPERTIES_HIBERNATE_CACHE_USE_MINIMAL_PUTS: 'false'
      SPRING_JPA_PROPERTIES_HIBERNATE_CACHE_GENERATE_STATISTICS: 'false'
      AWS_UPLOAD: 'false'
      DOCUMENT_UPLOAD_FILE_PATH: /home/vagrant/images
      DOCUMENT_LOCAL_UPLOAD_FILE_PATH: /home/vagrant/images
      DOCUMENT_PERMITTED_CONTENT_TYPES: application/pdf
    networks:
      - my-network

networks:
  my-network:
